export enum Routes {
  Root = '/',
  Contact = '/contact',
  Roadmap = 'https://achromatic.canny.io',
  Docs = '/docs',
  Pricing = '/#pricing',
  Blog = '/blog',
  Story = '/story',
  TermsOfUse = '/terms-of-use',
  PrivacyPolicy = '/privacy-policy',
  CookiePolicy = '/cookie-policy',

  Auth = '/auth',
  Login = '/auth/login',
  Logout = '/auth/logout',
  SignUp = '/auth/signup',
  AuthError = '/auth/error',
  Totp = '/auth/totp',
  RecoveryCode = '/auth/recovery-code',
  ChangeEmail = '/auth/change-email',
  ChangeEmailRequest = '/auth/change-email/request',
  ChangeEmailInvalid = '/auth/change-email/invalid',
  ChangeEmailExpired = '/auth/change-email/expired',
  ForgotPassword = '/auth/forgot-password',
  ForgotPasswordSuccess = '/auth/forgot-password/success',
  ResetPassword = '/auth/reset-password',
  ResetPasswordRequest = '/auth/reset-password/request',
  ResetPasswordExpired = '/auth/reset-password/expired',
  ResetPasswordSuccess = '/auth/reset-password/success',
  VerifyEmail = '/auth/verify-email',
  VerifyEmailRequest = '/auth/verify-email/request',
  VerifyEmailExpired = '/auth/verify-email/expired',
  VerifyEmailInvalid = '/auth/verify-email/invalid',
  VerifyEmailSuccess = '/auth/verify-email/success',

  Dashboard = '/dashboard',
  Home = '/dashboard/home',
  Documents = '/dashboard/documents',
  Contacts = '/dashboard/contacts',
  Billing = '/dashboard/billing',
  Settings = '/dashboard/settings',
  Account = '/dashboard/settings/account',
  Profile = '/dashboard/settings/account/profile',
  Security = '/dashboard/settings/account/security',
  Notifications = '/dashboard/settings/account/notifications',
  // Document-centric routes
  DocumentSettings = '/dashboard/settings/documents',
  DocumentSharing = '/dashboard/settings/documents/sharing',
  DocumentPreferences = '/dashboard/settings/documents/preferences',

  Onboarding = '/onboarding',

  // AI Tools routes
  AiChatbot = '/dashboard/ai-tools/chatbot',
  Flashcards = '/dashboard/ai-tools/flashcards',
  Summaries = '/dashboard/ai-tools/summaries',
  Quizzes = '/dashboard/ai-tools/quizzes',
  Podcasts = '/dashboard/ai-tools/podcasts',
  DocumentChat = '/dashboard/ai-tools/document-chat'
}
